version: '3'
services:
  mongo:
    image: mongo:3.6.17
    networks:
      - ns

  quality-script:
    build:
      context: .
      dockerfile: .docker/app/Dockerfile
      target: ci
      args:
        PYTHON_VERSION: focal-3-8
    command: sh ./bin/quality/${QUALITY_SCRIPT}.sh
    environment:
      - QUALITY_SCRIPT=${QUALITY_SCRIPT}
      - PYTHONPATH=/usr/src/app/
    volumes:
      - ./reports:/usr/src/app/reports
    networks:
      - ns
    depends_on:
      - mongo

  build-package:
    build:
      context: .
      dockerfile: .docker/app/Dockerfile
      target: prod-build
      args:
        PYTHON_VERSION: focal-3-8
    command: python setup.py sdist
    environment:
      - PYTHONPATH=/usr/src/app/
    volumes:
      - ./:/usr/src/app
    networks:
      - ns

  build-clean:
    build:
      context: .
      dockerfile: .docker/app/Dockerfile
      target: ci
      args:
        PYTHON_VERSION: focal-3-8
    command: rm -rf dist build *.egg-info
    environment:
      - PYTHONPATH=/usr/src/app/
    volumes:
      - ./:/usr/src/app
    networks:
      - ns

  devpi:
    image: quay.io/dailymotionadmin/devpi-server:latest
    volumes:
      - ./:/usr/src/app
    environment:
      - PYTHONPATH=/usr/src/app/
    networks:
      - ns

networks:
  ns:
